// <auto-generated />
using System;
using DSMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSMS.API.Migrations
{
    [DbContext(typeof(DsmsDbContext))]
    [Migration("20260405161227_Phase2_SchemaExpansion")]
    partial class Phase2_SchemaExpansion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DSMS.API.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentPackageRegistrationId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Bill__3214EC077A4C266D");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentPackageRegistrationId");

                    b.ToTable("Bill", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Branch__3214EC070DD6A432");

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NIC");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Employee__3214EC07");

                    b.HasIndex("BranchId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NIC");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Instruct__3214EC0722CA1438");

                    b.HasIndex("BranchId");

                    b.ToTable("Instructor", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("ChargePerExtraHour")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("CHargePerExtraHour");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DownPaymentAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxDiscount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Rmvcharges")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("RMVCharges");

                    b.Property<int>("TotLectureHours")
                        .HasColumnType("int");

                    b.Property<int>("TotTrainingHours")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Package__3214EC07B375D793");

                    b.ToTable("Package", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.PackageVehicleClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleClassId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PackageV__3214EC07B4A9C963");

                    b.HasIndex("PackageHeaderId");

                    b.HasIndex("VehicleClassId");

                    b.ToTable("PackageVehicleClass", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Payment__3214EC07D92CDDB7");

                    b.HasIndex("BillId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.RequiredDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Required__3214EC07C897CF9C");

                    b.ToTable("RequiredDocuments");
                });

            modelBuilder.Entity("DSMS.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC07D664BE92");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.SpecialRequirementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__SpecialR__3214EC074BBFFE7A");

                    b.ToTable("SpecialRequirementType", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExistingLicenseNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("HasBirthCertificate")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasNicCopy")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasNtmiMedical")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSpecialRequirements")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NearestDivisionalSecretariat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NearestPoliceStation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NIC");

                    b.Property<string>("PackageType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SpecialRequirementTypeId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WhatsAppNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Student__3214EC07DFCEA494");

                    b.HasIndex("BranchId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.StudentClassProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("HoursCompleted")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeclined")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTrialFaced")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PackageHeaderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentPackageRegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("TrialAttempt")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentC__3214EC07AA5E8745");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudentPackageRegistrationId");

                    b.ToTable("StudentClassProgress", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.StudentDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequiredDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentD__3214EC0751AB05B8");

                    b.HasIndex("RequiredDocumentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentDocuments");
                });

            modelBuilder.Entity("DSMS.API.Models.StudentPackageRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CompletedLectureHours")
                        .HasColumnType("int");

                    b.Property<int>("CompletedTrainingHours")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ExamAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDocumentSubmitted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRecommendForTrial")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TotalLectureHours")
                        .HasColumnType("int");

                    b.Property<int>("TotalTrainingHours")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentP__3214EC078C9EC726");

                    b.HasIndex("PackageHeaderId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentPackageRegistration", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.StudentPracticalTestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentClassProgressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__StudentP__3214EC07022D1477");

                    b.HasIndex("StudentClassProgressId");

                    b.ToTable("StudentPracticalTestAttempt", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.StudentVehicleClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleClassCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentVehicleClass", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.TrainingAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReadyForPracticalTest")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StudentPackageRegistrationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudentPackageRegistrationId");

                    b.ToTable("TrainingAttendance", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC0705BB4141");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.UserSecurity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ActiveStatusChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ActiveStatusChangedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("FirstTimeLogin")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PasswordExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__UserSecu__3214EC073343E162");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSecurity", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.VehicleClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LectureHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrainingHours")
                        .HasColumnType("int");

                    b.Property<string>("VehicleTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__VehicleC__3214EC0779DE42EA");

                    b.ToTable("VehicleClass", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__VehicleT__3214EC079450D4A5");

                    b.ToTable("VehicleType", (string)null);
                });

            modelBuilder.Entity("DSMS.API.Models.Bill", b =>
                {
                    b.HasOne("DSMS.API.Models.Student", "Student")
                        .WithMany("Bills")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Bill_Student");

                    b.HasOne("DSMS.API.Models.StudentPackageRegistration", "StudentPackageRegistration")
                        .WithMany("Bills")
                        .HasForeignKey("StudentPackageRegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK_Bill_SPR");

                    b.Navigation("Student");

                    b.Navigation("StudentPackageRegistration");
                });

            modelBuilder.Entity("DSMS.API.Models.Employee", b =>
                {
                    b.HasOne("DSMS.API.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Branch");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("DSMS.API.Models.Instructor", b =>
                {
                    b.HasOne("DSMS.API.Models.Branch", "Branch")
                        .WithMany("Instructors")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Instructor_Branch");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("DSMS.API.Models.PackageVehicleClass", b =>
                {
                    b.HasOne("DSMS.API.Models.Package", "PackageHeader")
                        .WithMany("PackageVehicleClasses")
                        .HasForeignKey("PackageHeaderId")
                        .IsRequired()
                        .HasConstraintName("FK_PVC_Package");

                    b.HasOne("DSMS.API.Models.VehicleClass", "VehicleClass")
                        .WithMany("PackageVehicleClasses")
                        .HasForeignKey("VehicleClassId")
                        .IsRequired()
                        .HasConstraintName("FK_PVC_VehicleClass");

                    b.Navigation("PackageHeader");

                    b.Navigation("VehicleClass");
                });

            modelBuilder.Entity("DSMS.API.Models.Payment", b =>
                {
                    b.HasOne("DSMS.API.Models.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Bill");

                    b.HasOne("DSMS.API.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Student");

                    b.Navigation("Bill");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DSMS.API.Models.Student", b =>
                {
                    b.HasOne("DSMS.API.Models.Branch", "Branch")
                        .WithMany("Students")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Student_Branch");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("DSMS.API.Models.StudentClassProgress", b =>
                {
                    b.HasOne("DSMS.API.Models.Instructor", "Instructor")
                        .WithMany("StudentClassProgresses")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("FK_SCP_Instructor");

                    b.HasOne("DSMS.API.Models.StudentPackageRegistration", "StudentPackageRegistration")
                        .WithMany("StudentClassProgresses")
                        .HasForeignKey("StudentPackageRegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK_SCP_SPR");

                    b.Navigation("Instructor");

                    b.Navigation("StudentPackageRegistration");
                });

            modelBuilder.Entity("DSMS.API.Models.StudentDocument", b =>
                {
                    b.HasOne("DSMS.API.Models.RequiredDocument", "RequiredDocument")
                        .WithMany("StudentDocuments")
                        .HasForeignKey("RequiredDocumentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentDocs_RequiredDocs");

                    b.HasOne("DSMS.API.Models.Student", "Student")
                        .WithMany("StudentDocuments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentDocs_Student");

                    b.Navigation("RequiredDocument");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DSMS.API.Models.StudentPackageRegistration", b =>
                {
                    b.HasOne("DSMS.API.Models.Package", "PackageHeader")
                        .WithMany("StudentPackageRegistrations")
                        .HasForeignKey("PackageHeaderId")
                        .IsRequired()
                        .HasConstraintName("FK_SPR_Package");

                    b.HasOne("DSMS.API.Models.Student", "Student")
                        .WithMany("StudentPackageRegistrations")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_SPR_Student");

                    b.Navigation("PackageHeader");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DSMS.API.Models.StudentPracticalTestAttempt", b =>
                {
                    b.HasOne("DSMS.API.Models.StudentClassProgress", "StudentClassProgress")
                        .WithMany("StudentPracticalTestAttempts")
                        .HasForeignKey("StudentClassProgressId")
                        .IsRequired()
                        .HasConstraintName("FK_SPTA_SCP");

                    b.Navigation("StudentClassProgress");
                });

            modelBuilder.Entity("DSMS.API.Models.StudentVehicleClass", b =>
                {
                    b.HasOne("DSMS.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_SVC_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DSMS.API.Models.TrainingAttendance", b =>
                {
                    b.HasOne("DSMS.API.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("FK_TA_Instructor");

                    b.HasOne("DSMS.API.Models.StudentPackageRegistration", "StudentPackageRegistration")
                        .WithMany()
                        .HasForeignKey("StudentPackageRegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK_TA_SPR");

                    b.Navigation("Instructor");

                    b.Navigation("StudentPackageRegistration");
                });

            modelBuilder.Entity("DSMS.API.Models.User", b =>
                {
                    b.HasOne("DSMS.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DSMS.API.Models.UserSecurity", b =>
                {
                    b.HasOne("DSMS.API.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK_UserSecurity_Branch");

                    b.HasOne("DSMS.API.Models.Role", "Role")
                        .WithMany("UserSecurities")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserSecurity_Role");

                    b.HasOne("DSMS.API.Models.User", "User")
                        .WithMany("UserSecurities")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserSecurity_User");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DSMS.API.Models.Bill", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DSMS.API.Models.Branch", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("DSMS.API.Models.Instructor", b =>
                {
                    b.Navigation("StudentClassProgresses");
                });

            modelBuilder.Entity("DSMS.API.Models.Package", b =>
                {
                    b.Navigation("PackageVehicleClasses");

                    b.Navigation("StudentPackageRegistrations");
                });

            modelBuilder.Entity("DSMS.API.Models.RequiredDocument", b =>
                {
                    b.Navigation("StudentDocuments");
                });

            modelBuilder.Entity("DSMS.API.Models.Role", b =>
                {
                    b.Navigation("UserSecurities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DSMS.API.Models.Student", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Payments");

                    b.Navigation("StudentDocuments");

                    b.Navigation("StudentPackageRegistrations");
                });

            modelBuilder.Entity("DSMS.API.Models.StudentClassProgress", b =>
                {
                    b.Navigation("StudentPracticalTestAttempts");
                });

            modelBuilder.Entity("DSMS.API.Models.StudentPackageRegistration", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("StudentClassProgresses");
                });

            modelBuilder.Entity("DSMS.API.Models.User", b =>
                {
                    b.Navigation("UserSecurities");
                });

            modelBuilder.Entity("DSMS.API.Models.VehicleClass", b =>
                {
                    b.Navigation("PackageVehicleClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
